name: Publish

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: ./gradlew build

      - name: Archive Artifacts (fabric)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: BedrockSkinUtility
          path: build/libs/BedrockSkinUtility-*.jar
          if-no-files-found: error
